on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: cargo hakari

jobs:
  workspace-hack-check:
    name: Check workspace-hack
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-search2
        id: install-cargo-search2
        run: |
          curl -LsSf https://github.com/sunshowers/cargo-search2/releases/latest/download/cargo-search2-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
        shell: bash
      - name: Get cargo-hakari version
        id: cargo-hakari-version
        run: |
          cargo search2 cargo-hakari --req 0.9 --message-format github
        shell: bash
      - name: Attempt to load cached cargo-hakari
        uses: actions/cache@v2
        id: cargo-hakari-cache
        with:
          path: |
            ~/.cargo/bin/cargo-hakari
            ~/.cargo/bin/cargo-hakari.exe
          key: ${{ runner.os }}-${{ steps.cargo-hakari-version.outputs.hash }}
      - name: Install cargo-hakari
        if: steps.cargo-hakari-cache.outputs.cache-hit != 'true'
        uses: actions-rs/install@v0.1.2
        with:
          crate: cargo-hakari
          version: ${{ steps.cargo-hakari-version.outputs.version }}

      - name: Check workspace-hack Cargo.toml is up-to-date
        uses: actions-rs/cargo@v1
        with:
          command: hakari
          args: generate --diff
      - name: Check all crates depend on workspace-hack
        uses: actions-rs/cargo@v1
        with:
          command: hakari
          args: manage-deps --dry-run
